sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: WonrtMPUbTsWLv2rZj+97+Pu4bpRWqPECzHDnxiOKCqcKa4Ir5ve7Wm/CY1B/1rMLGH2K8NO1nxnCV9CQiolCGv3OSCuFUfpiwgwC85kZxE61N27yeBGn9oltm5zA74rfMDPHmDuPtcFbVRbV/cKHgx+FjB/F04BhjKfcsjOOYPOsRN6fitl/nBL+/q5JxQexs4L9ztBCXzAL/kEgHIN+oSm7r84fxIVN3bUtT5deoMzmAphdtZJgf6cfNXauMiCzVVpadPwBvnla+N89ntF8dswuqlGKtZNSwsLCWlUbH95xB8Ennan0iPNetFZa6SWSWGl1kHWnbkDVoTCyDHaajKETgBQUYXw6Od33skoMGxFT9dm1AphdhlRXea6cvBCWvgZzwBbQlv5T6AXDci2nVT+5JA829EfgxC3yTNT/vj3U9dbliId7ZseCWaCoPH0NqNP4WIIwtBu1YUhGYEj1KgqTE/e+tt7sEPSrJJqz5R+U1ZFpOfPBTFBOUo5PnkGQLafgPPNv2x5iIQTi//heabwJnGHO6ROFD6/CSCFStoqco1L9MloHCMbZbaVSgWmaeegIRF9Q0JBG9JD6eSoxCT5OcUxbLrT3i9ff0+G45IjN2rYhRB4mIFpwEuPzEQcsuqE23SpBiYXjWIvKkz+7Pzp0l1hXEvLSYtE1NQzbro=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: G823yerahnngbH+j0eNiI30vLL5elrOtwH6jGZIiza/+QS5sH8MRF8gJhdbq1knh/wT5DhLnQpv4CI1rkFOhqLlh260kQ9aSQ4Cab0w7ftDQ1385Rg6s/GyA9oQULkTIV4p046UfbSa2cfxhnlhphRjP6dtLyVW+2MxqrtV3izAVKLnTtpQswwKpQfULDt3JtSgrABaToBOa0rjNG2dJQEXoZ+Cw80MTJEN4DlugYaU7PzXO7AhzOHdhvFCcgXAn9EerUTHBcNq4JiNVzomAuS3bR2SWajUz71qtPfUtERyTGTuSGX8Kougks1jnVSsgnRfndILxH4jq7JkS85OrnNaDmBdD5X66yePcQBY98duh0s5zRIHoV1YWWVdLKL2oWaAWhtBd1FlzA3kfCx1gP3VGKC/NeQoKtgi2Ef210VD4RdCbOrDFDBE5iLjfDu1rYcWE+n7D9EB7XBeyDEVLfBD4o0QLh2LLhyGLpGbng+rrh9O+9V8AqoNgxE7jpwJBRRkLWzXloAw9PhUiO9Vw+EEsdc1yZWo1qu8aMB6voBBlZya+1wW8dlIqqzGeSec0hMBOiXZOChW5h6rjwEDnxaWy3Ubt/aGrYjGukgjCEtzNMWnSWZB3OSk6WnGVtCbuDva58hJhr8y5wI8xfkVpYHguhrQi9QXesetnpxy2hvI=
